version: '{build}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
  project: OutlookMatters.sln
    - cmd: msbuild OutlookMatter.sln
after_test:
    - cmd: .\scripts\coverage.cmd
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f results.xml
